### ISSUE TITLE
Creating TXT record through REST API fails with a 5005 Missing type property data

### ISSUE THREAD

**Issue by johnneerdael** [ctxis/SnitchDNS#8]
JSON object to add:
`{
   "class":"IN",
   "type":"TXT",
   "ttl":3600,
   "active":true,
   "data":{
      "data":"text-string"
   },
   "is_conditional":false,
   "conditional_count":0,
   "conditional_limit":0,
   "conditional_reset":false,
   "conditional_data":{
   }
}`

Error:
`{
    "code": 5005,
    "details": [
        "Missing type property data"
    ],
    "message": "Invalid type property fields",
    "success": false
}`

**Comment by sadreck** [comment]
could you paste here the full HTTP request please? As in the HTTP Endpoint, HTTP Method, and the full body

**Comment by johnneerdael** [comment]
`curl -k -X 'POST' 'https://privatedomain/api/v1/zones/70chars.johnneerdael.dataexfiltration.privatedomain/records' -H 'accept: application/json' -H 'X-SnitchDNS-Auth: APIKEY' -H 'Content-Type: application/json'  -d '{"class":"IN","type":"TXT","ttl":3600,"active":true,"data":{"data":"text-string"},"is_conditional":false,"conditional_count":0,"conditional_limit":0,"conditional_reset":false,"conditional_data":{}}'`

**Comment by sadreck** [comment]
Thanks for reporting this, I've now pushed a fix - please pull the latest and greatest and give it another go.

The issue was that it was looking for conditional data although the `is_conditional` parameter was set to false.

I'll close the ticket now - if there are any other issues feel free to open it again.
